from . import res_partner
from . import sale
from . import delivery_picking
from . import work_details
from . import settlements
from . import product
from . import account
from . import settings
from . import purchase
from . import res_users
from . import shipping_method
from . import delivery_time_slot
from . import banners
from . import res_company
